/**
 * King County, Washington — Housing Resource Directory
 *
 * IMPORTANT: Program details, phone numbers, eligibility, and hours
 * change frequently. All resources should be verified before use.
 * Items marked needsVerification: true require current confirmation.
 *
 * Sources used: 211 WA, King County DCHS, Washington State DSHS,
 * individual organization websites. Last reviewed: 2024.
 */

export const resources = [

  /* ============================================================
     CRISIS & IMMEDIATE HELP
  ============================================================ */
  {
    id: 'wa211',
    name: '211 Washington — Housing & Social Services Hotline',
    category: 'crisis',
    tags: ['crisis', 'referral', 'housing', 'utilities', 'food', 'all-counties'],
    description: 'Free, confidential referral service. Call or text 211 to reach a specialist 24/7 who can connect you to local housing, utility, food, and crisis resources.',
    phone: '211',
    phone_alt: '1-800-223-1880',
    website: null,
    hours: '24 hours, 7 days a week',
    languages: 'Multiple languages available',
    eligibility: 'Anyone in Washington State',
    cost: 'Free',
    notes: 'Best first call. 211 specialists know current availability of shelter, rental assistance, and emergency programs.',
    needsVerification: false,
    priority: 1,
    urgentFlag: true,
  },
  {
    id: 'kc-coordinated-entry',
    name: 'King County Coordinated Entry — Path to Housing',
    category: 'crisis',
    tags: ['homeless', 'shelter', 'housing', 'coordinated-entry', 'king-county'],
    description: 'The entry point for homeless services in King County. If you are homeless or at imminent risk, this is how to access shelters, transitional housing, and housing programs.',
    phone: '206-328-5755',
    phone_alt: null,
    website: null,
    hours: 'Varies by intake location — call 211 first to confirm current access point',
    languages: 'Multiple languages',
    eligibility: 'People experiencing homelessness or at imminent risk in King County',
    cost: 'Free',
    notes: 'Coordinated Entry assigns a "vulnerability score" to connect people to the most appropriate housing resource. Call 211 to find current access points.',
    needsVerification: true,
    verifyNote: 'Coordinated Entry access points and phone numbers change. Verify current intake points via 211 or King County DCHS.',
    priority: 1,
    urgentFlag: true,
  },

  /* ============================================================
     EMERGENCY SHELTER
  ============================================================ */
  {
    id: 'desc',
    name: 'DESC — Downtown Emergency Service Center',
    category: 'shelter',
    tags: ['shelter', 'housing', 'mental-health', 'disability', 'adult', 'seattle'],
    description: 'Provides emergency shelter, housing, and mental health/substance use services for adults experiencing chronic homelessness in Seattle.',
    phone: '206-464-1570',
    phone_alt: null,
    website: null,
    hours: 'Call for current availability and access',
    languages: 'English; interpreter services available',
    eligibility: 'Adults 18+, often focus on chronic homelessness and behavioral health needs',
    cost: 'Free',
    notes: 'Operates multiple shelter and housing programs. Also provides outreach.',
    needsVerification: true,
    verifyNote: 'Shelter bed availability changes daily. Call directly or through 211.',
    priority: 1,
    urgentFlag: true,
  },
  {
    id: 'compass-housing',
    name: 'Compass Housing Alliance',
    category: 'shelter',
    tags: ['shelter', 'transitional-housing', 'case-management', 'king-county'],
    description: 'Emergency shelter, transitional housing, and supportive services for single adults and families experiencing homelessness.',
    phone: '206-474-1100',
    phone_alt: null,
    website: null,
    hours: 'Call for current availability',
    languages: 'English; other languages may be available',
    eligibility: 'Single adults and families; specific eligibility varies by program',
    cost: 'Free',
    needsVerification: true,
    verifyNote: 'Program availability and intake process changes. Verify via 211 or direct call.',
    priority: 1,
    urgentFlag: false,
  },
  {
    id: 'ywca-shelter',
    name: 'YWCA Seattle | King | Snohomish — Emergency Housing',
    category: 'shelter',
    tags: ['shelter', 'domestic-violence', 'women', 'families', 'children', 'king-county'],
    description: 'Emergency shelter, transitional housing, and supportive services for survivors of domestic violence and families.',
    phone: '206-461-4882',
    phone_alt: '1-888-293-2222',
    website: null,
    hours: '24-hour crisis line',
    languages: 'Multiple languages available',
    eligibility: 'Women, families, DV survivors; specific programs vary',
    cost: 'Free',
    notes: 'Provides safety planning, advocacy, and housing navigation in addition to shelter.',
    needsVerification: true,
    verifyNote: 'Verify current capacity, intake procedures, and available programs.',
    priority: 1,
    urgentFlag: true,
  },

  /* ============================================================
     DOMESTIC VIOLENCE & SAFETY
  ============================================================ */
  {
    id: 'dawn-dv',
    name: 'DAWN — Domestic Abuse Women\'s Network',
    category: 'safety',
    tags: ['domestic-violence', 'safety', 'shelter', 'south-king-county', 'advocacy'],
    description: '24-hour crisis line, emergency shelter, transitional housing, and advocacy for survivors of domestic violence in South King County.',
    phone: '425-656-8423',
    phone_alt: null,
    website: null,
    hours: '24 hours, 7 days a week',
    languages: 'English and Spanish; interpreter services available',
    eligibility: 'Survivors of domestic violence in South King County',
    cost: 'Free',
    notes: 'DAWN can help with safety planning, emergency housing, and connection to longer-term resources.',
    needsVerification: false,
    priority: 1,
    urgentFlag: true,
  },
  {
    id: 'wa-dv-hotline',
    name: 'Washington State Domestic Violence Hotline',
    category: 'safety',
    tags: ['domestic-violence', 'crisis', 'statewide'],
    description: '24-hour statewide domestic violence crisis and referral line.',
    phone: '1-800-562-6025',
    phone_alt: null,
    website: null,
    hours: '24 hours, 7 days a week',
    languages: 'Multiple languages available',
    eligibility: 'Anyone experiencing domestic violence in Washington State',
    cost: 'Free',
    needsVerification: false,
    priority: 1,
    urgentFlag: true,
  },
  {
    id: 'national-dv-hotline',
    name: 'National Domestic Violence Hotline',
    category: 'safety',
    tags: ['domestic-violence', 'crisis', 'national', 'text'],
    description: '24/7 crisis support, safety planning, and resource referrals.',
    phone: '1-800-799-7233',
    phone_alt: 'Text START to 88788',
    website: null,
    hours: '24 hours, 7 days a week',
    languages: 'Multiple languages; online chat available',
    eligibility: 'Anyone',
    cost: 'Free',
    notes: 'Chat option available if calling is not safe.',
    needsVerification: false,
    priority: 1,
    urgentFlag: true,
  },

  /* ============================================================
     EVICTION PREVENTION & LEGAL AID
  ============================================================ */
  {
    id: 'nwjp',
    name: 'Northwest Justice Project — Legal Aid',
    category: 'legal',
    tags: ['legal-aid', 'eviction', 'tenant-rights', 'housing', 'king-county', 'statewide'],
    description: 'Free civil legal help for low-income people in Washington State. Handles eviction defense, housing cases, public benefits, and more.',
    phone: '1-888-201-1014',
    phone_alt: null,
    website: null,
    hours: 'Call for current intake hours',
    languages: 'Multiple languages; interpreter services available',
    eligibility: 'Low-income individuals and families in Washington State',
    cost: 'Free',
    notes: 'If you have an eviction court date, call immediately. They may be able to represent you or provide advice.',
    needsVerification: true,
    verifyNote: 'Intake hours and eligibility guidelines may change. Verify current procedure before referring.',
    priority: 1,
    urgentFlag: true,
  },
  {
    id: 'tenants-union',
    name: 'Tenants Union of Washington State',
    category: 'legal',
    tags: ['tenant-rights', 'eviction', 'counseling', 'education', 'king-county'],
    description: 'Tenant rights counseling, eviction prevention, and housing education. Hotline available for tenants facing housing problems.',
    phone: '206-723-0500',
    phone_alt: null,
    website: null,
    hours: 'Varies — call or check website for current hours',
    languages: 'English; limited other languages',
    eligibility: 'Tenants in King County; some statewide services',
    cost: 'Free (donations accepted)',
    notes: 'Excellent resource for understanding your legal rights before calling an attorney.',
    needsVerification: true,
    verifyNote: 'Hours and intake procedures change. Verify current availability.',
    priority: 1,
    urgentFlag: false,
  },
  {
    id: 'columbia-legal',
    name: 'Columbia Legal Services',
    category: 'legal',
    tags: ['legal-aid', 'housing', 'benefits', 'disability', 'statewide'],
    description: 'Free legal help for low-income Washington residents with housing, public benefits, disability rights, and more.',
    phone: '1-888-201-1014',
    phone_alt: null,
    website: null,
    hours: 'Call for intake information',
    languages: 'Multiple languages',
    eligibility: 'Low-income individuals and families in Washington State',
    cost: 'Free',
    needsVerification: true,
    verifyNote: 'Intake and program availability change. Verify current procedures.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'kcba-lawyer-referral',
    name: 'King County Bar Association — Lawyer Referral Service',
    category: 'legal',
    tags: ['legal', 'attorney', 'referral', 'king-county'],
    description: 'Referral to a local attorney for a reduced-cost initial consultation.',
    phone: '206-267-7010',
    phone_alt: null,
    website: null,
    hours: 'Call for current hours',
    languages: 'English',
    eligibility: 'Anyone; fee applies for referral consultation (not free legal aid)',
    cost: 'Reduced-fee initial consultation; full fees after',
    notes: 'This is not free legal aid — it is a referral service. For free help see Northwest Justice Project.',
    needsVerification: true,
    verifyNote: 'Fees and availability change. Verify before referring.',
    priority: 3,
    urgentFlag: false,
  },

  /* ============================================================
     RENTAL ASSISTANCE
  ============================================================ */
  {
    id: 'solid-ground',
    name: 'Solid Ground — Rental & Housing Assistance',
    category: 'rental-assistance',
    tags: ['rental-assistance', 'eviction-prevention', 'housing', 'food', 'king-county'],
    description: 'Rental assistance, housing case management, eviction prevention, food, and other basic needs programs for King County residents.',
    phone: '206-694-6700',
    phone_alt: null,
    website: null,
    hours: 'Call for current program availability',
    languages: 'Multiple languages available',
    eligibility: 'Low-income King County residents; specific eligibility varies by program',
    cost: 'Free',
    notes: 'Solid Ground offers both emergency rental assistance and ongoing housing stability support.',
    needsVerification: true,
    verifyNote: 'Rental assistance funding cycles. Confirm current availability and eligibility before referring.',
    priority: 1,
    urgentFlag: false,
  },
  {
    id: 'kc-hcdd',
    name: 'King County Housing & Community Development — Emergency Rental Assistance',
    category: 'rental-assistance',
    tags: ['rental-assistance', 'eviction-prevention', 'king-county', 'county-program'],
    description: 'King County administers emergency rental and utility assistance programs. Programs and funding change based on available resources.',
    phone: '206-263-9100',
    phone_alt: null,
    website: null,
    hours: 'Call for current program status',
    languages: 'Multiple languages available',
    eligibility: 'King County residents; income-limited; specific criteria vary by program',
    cost: 'Free',
    notes: 'Programs may open and close based on funding. Call 211 first to find currently active programs.',
    needsVerification: true,
    verifyNote: 'Emergency rental assistance programs are funded through federal/state appropriations that change frequently. Always verify current open programs via 211.',
    priority: 1,
    urgentFlag: false,
  },
  {
    id: 'ccs-assistance',
    name: 'Catholic Community Services — Housing & Basic Needs',
    category: 'rental-assistance',
    tags: ['rental-assistance', 'housing', 'basic-needs', 'emergency', 'king-county'],
    description: 'Emergency rental and utility assistance, housing navigation, and basic needs support for King County residents.',
    phone: '206-323-6336',
    phone_alt: null,
    website: null,
    hours: 'Call for current intake hours',
    languages: 'Multiple languages; Spanish services available',
    eligibility: 'Low-income King County residents regardless of faith background',
    cost: 'Free',
    needsVerification: true,
    verifyNote: 'Program availability and funding vary. Verify current assistance programs.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'salvation-army',
    name: 'Salvation Army — Emergency Financial Assistance',
    category: 'rental-assistance',
    tags: ['rental-assistance', 'utilities', 'emergency', 'king-county'],
    description: 'Emergency financial assistance for rent, utilities, and basic needs.',
    phone: '206-587-0503',
    phone_alt: null,
    website: null,
    hours: 'Call for current intake hours and availability',
    languages: 'English; other languages may be available',
    eligibility: 'Varies by program; income-limited',
    cost: 'Free',
    notes: 'Multiple Salvation Army locations in King County. Call 211 to find the nearest one with current funding.',
    needsVerification: true,
    verifyNote: 'Emergency assistance funding varies. Verify current availability.',
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     UTILITY ASSISTANCE
  ============================================================ */
  {
    id: 'liheap',
    name: 'LIHEAP — Low Income Home Energy Assistance Program',
    category: 'utilities',
    tags: ['utilities', 'heating', 'cooling', 'energy', 'federal', 'statewide'],
    description: 'Federal program providing heating and cooling assistance to low-income households. Administered in Washington through DSHS and local community agencies.',
    phone: '1-800-865-7801',
    phone_alt: '211',
    website: null,
    hours: 'Call for current program open dates — seasonal',
    languages: 'Multiple languages available',
    eligibility: 'Income-limited households; generally up to 150% of federal poverty level (Needs Verification)',
    cost: 'Free',
    notes: 'LIHEAP has application windows — typically fall/winter. Call early. Some crisis assistance available year-round for utility shutoff emergencies.',
    needsVerification: true,
    verifyNote: 'Eligibility thresholds and program open dates change annually. Verify via DSHS or local provider.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'pse-assistance',
    name: 'Puget Sound Energy — Customer Assistance Programs',
    category: 'utilities',
    tags: ['utilities', 'electric', 'gas', 'assistance', 'king-county'],
    description: 'PSE offers bill assistance, payment arrangements, and low-income rate programs for eligible customers. Contact PSE directly if facing shutoff.',
    phone: '1-888-225-5773',
    phone_alt: null,
    website: null,
    hours: 'Business hours; call for current program info',
    languages: 'Multiple languages; phone interpreter',
    eligibility: 'PSE customers; income-based for discount programs',
    cost: 'Free assistance programs; rate discounts available',
    notes: 'Ask specifically about: (1) payment arrangements, (2) budget billing, (3) HELP program (low-income discount), (4) Project SHARE (emergency assistance).',
    needsVerification: true,
    verifyNote: 'PSE program names and eligibility change. Verify current assistance programs directly with PSE.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'scl-assistance',
    name: 'Seattle City Light — Customer Assistance',
    category: 'utilities',
    tags: ['utilities', 'electric', 'assistance', 'seattle'],
    description: 'Seattle City Light offers discount programs and assistance for low-income customers, including the Utility Discount Program (UDP).',
    phone: '206-684-3000',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages available',
    eligibility: 'Seattle City Light customers with income at or below 70% of AMI (Needs Verification)',
    cost: 'Free discount program',
    notes: 'Ask about the Utility Discount Program. Also contact Seattle Public Utilities (SPU) about water/sewer discounts at same time.',
    needsVerification: true,
    verifyNote: 'UDP eligibility and discount amounts change. Verify current program rules.',
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     AFFORDABLE HOUSING — WAITLISTS & APPLICATIONS
  ============================================================ */
  {
    id: 'kcha',
    name: 'King County Housing Authority (KCHA)',
    category: 'affordable-housing',
    tags: ['housing-authority', 'section-8', 'voucher', 'affordable-housing', 'public-housing', 'king-county'],
    description: 'Administers federal housing voucher programs (Section 8/HCV) and public housing in King County outside Seattle. Manages affordable housing properties.',
    phone: '206-214-1300',
    phone_alt: null,
    website: null,
    hours: 'Business hours; call for waitlist status',
    languages: 'Multiple languages available',
    eligibility: 'Income-limited households; waitlists often closed — call for current status',
    cost: 'Subsidized (tenant pays 30% of income)',
    notes: 'KCHA waitlists are frequently closed and can have multi-year wait times. Inquire about any open waitlists or emergency preferences.',
    needsVerification: true,
    verifyNote: 'Waitlist availability changes. Verify current open waitlists and any lottery or preference categories.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'sha',
    name: 'Seattle Housing Authority (SHA)',
    category: 'affordable-housing',
    tags: ['housing-authority', 'section-8', 'voucher', 'public-housing', 'seattle'],
    description: 'Administers federal housing vouchers and public housing for Seattle residents. Manages affordable housing properties.',
    phone: '206-615-3300',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages available',
    eligibility: 'Income-limited; preference for Seattle residents; waitlists often closed',
    cost: 'Subsidized',
    notes: 'SHA voucher and public housing waitlists may be closed. Ask about any currently open programs or special admission categories.',
    needsVerification: true,
    verifyNote: 'Waitlist status changes. Verify current openings.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'plymouth-housing',
    name: 'Plymouth Housing — Permanent Supportive Housing',
    category: 'affordable-housing',
    tags: ['permanent-supportive-housing', 'chronically-homeless', 'disability', 'adults', 'seattle'],
    description: 'Permanent supportive housing for chronically homeless adults with disabilities or other vulnerabilities. Case management services included.',
    phone: '206-374-9409',
    phone_alt: null,
    website: null,
    hours: 'Call for referral process information',
    languages: 'English; interpreter services available',
    eligibility: 'Chronically homeless adults; typically referred through Coordinated Entry',
    cost: 'Income-based',
    notes: 'Referrals typically come through Coordinated Entry. Call to understand current access process.',
    needsVerification: true,
    verifyNote: 'Referral processes change. Verify current intake through Coordinated Entry or direct contact.',
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     DISABILITY & ACCOMMODATION
  ============================================================ */
  {
    id: 'wshrc',
    name: 'Washington State Human Rights Commission',
    category: 'disability',
    tags: ['disability', 'fair-housing', 'discrimination', 'complaint', 'statewide'],
    description: 'Investigates complaints of housing discrimination including disability discrimination and failure to provide reasonable accommodations.',
    phone: '1-800-233-3247',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages',
    eligibility: 'Anyone who believes they have experienced housing discrimination in Washington State',
    cost: 'Free',
    notes: 'File a complaint if a landlord has denied a reasonable accommodation request or discriminated based on disability, familial status, or other protected class.',
    needsVerification: true,
    verifyNote: 'Verify current complaint process and deadlines (complaint filing deadlines apply).',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'fhcw',
    name: 'Fair Housing Center of Washington',
    category: 'disability',
    tags: ['fair-housing', 'discrimination', 'education', 'advocacy', 'statewide'],
    description: 'Provides housing discrimination testing, education, and advocacy. Can assist with fair housing complaints.',
    phone: '425-774-1630',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'English; interpreter services available',
    eligibility: 'Anyone in Washington State',
    cost: 'Free',
    needsVerification: true,
    verifyNote: 'Verify current contact information and services.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'hud-fheo',
    name: 'HUD — Office of Fair Housing and Equal Opportunity',
    category: 'disability',
    tags: ['fair-housing', 'discrimination', 'federal', 'complaint'],
    description: 'Federal office that investigates housing discrimination complaints under the Fair Housing Act.',
    phone: '1-800-669-9777',
    phone_alt: '1-800-927-9275 (TTY)',
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages',
    eligibility: 'Anyone who believes they have experienced housing discrimination',
    cost: 'Free',
    notes: 'Fair Housing Act complaints must be filed within one year of the discriminatory act.',
    needsVerification: false,
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     FOOD & BASIC NEEDS
  ============================================================ */
  {
    id: 'food-banks',
    name: 'FoodLifeline / Local Food Banks',
    category: 'food',
    tags: ['food', 'basic-needs', 'king-county'],
    description: 'King County has a network of food banks and food pantries. Call 211 to find the nearest food bank with current hours.',
    phone: '211',
    phone_alt: null,
    website: null,
    hours: 'Varies by location',
    languages: 'Varies by location',
    eligibility: 'Anyone in need; most have no income requirements',
    cost: 'Free',
    notes: 'Call 211 for the nearest food bank. Many do not require ID or proof of residency.',
    needsVerification: false,
    priority: 3,
    urgentFlag: false,
  },
  {
    id: 'dshs-snap',
    name: 'DSHS — Basic Food (SNAP) and Other Benefits',
    category: 'food',
    tags: ['food', 'snap', 'basic-food', 'benefits', 'dshs', 'statewide'],
    description: 'Washington\'s Basic Food program (SNAP) provides monthly food assistance. DSHS also provides TANF, childcare, and other supports.',
    phone: '1-877-501-2233',
    phone_alt: null,
    website: null,
    hours: 'Business hours; online applications available 24/7',
    languages: 'Multiple languages available',
    eligibility: 'Income-limited households; no citizenship requirement for some programs',
    cost: 'Free benefits',
    notes: 'Apply online at WashingtonConnection.org. Emergency food benefits may be available within 7 days for households in extreme hardship.',
    needsVerification: true,
    verifyNote: 'Income limits and emergency procedures change. Verify current eligibility and processing timelines.',
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     HEALTH & BEHAVIORAL HEALTH
  ============================================================ */
  {
    id: 'neighborcare',
    name: 'Neighborcare Health',
    category: 'health',
    tags: ['health', 'mental-health', 'healthcare', 'primary-care', 'sliding-scale', 'seattle'],
    description: 'Federally Qualified Health Center providing primary care, mental health, dental, and other services on a sliding-fee scale.',
    phone: '206-461-6900',
    phone_alt: null,
    website: null,
    hours: 'Call for current hours and new patient availability',
    languages: 'Multiple languages available',
    eligibility: 'Anyone; fees are on a sliding scale based on income',
    cost: 'Sliding scale; no one turned away for inability to pay',
    needsVerification: true,
    verifyNote: 'Capacity and hours change. Verify current new patient availability.',
    priority: 3,
    urgentFlag: false,
  },
  {
    id: 'crisis-connections',
    name: 'Crisis Connections — 24-Hour Crisis Line',
    category: 'health',
    tags: ['mental-health', 'crisis', 'suicide', 'king-county'],
    description: '24-hour mental health crisis line for King County. Immediate support and connection to crisis services.',
    phone: '866-427-4747',
    phone_alt: null,
    website: null,
    hours: '24 hours, 7 days a week',
    languages: 'Multiple languages; interpreter available',
    eligibility: 'Anyone in King County',
    cost: 'Free',
    needsVerification: false,
    priority: 1,
    urgentFlag: true,
  },

  /* ============================================================
     CHILDREN & FAMILIES
  ============================================================ */
  {
    id: 'school-stability',
    name: 'McKinney-Vento School Stability Rights',
    category: 'family',
    tags: ['children', 'school', 'homeless', 'education', 'family', 'rights'],
    description: 'Under the McKinney-Vento Homeless Assistance Act, children experiencing homelessness have the right to stay enrolled in their school of origin. Contact your school district\'s McKinney-Vento liaison.',
    phone: null,
    phone_alt: 'Contact your school district office',
    website: null,
    hours: 'During school hours',
    languages: 'Varies by district',
    eligibility: 'Children and youth experiencing homelessness or housing instability',
    cost: 'Free (required by law)',
    notes: 'Key rights: stay in school of origin, immediate enrollment even without documents, transportation assistance. Each school district must have a designated liaison.',
    needsVerification: true,
    verifyNote: 'Contact your specific school district for their McKinney-Vento liaison contact information. King County has multiple school districts.',
    priority: 2,
    urgentFlag: false,
  },
  {
    id: 'childcare-assistance',
    name: 'DCYF — Childcare Assistance Program (CCAP)',
    category: 'family',
    tags: ['childcare', 'family', 'work-support', 'income', 'statewide'],
    description: 'Washington State subsidized childcare for working families and families in job training or school.',
    phone: '1-844-626-8687',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages',
    eligibility: 'Income-limited working families; children under 13 (Needs Verification)',
    cost: 'Subsidized; copay based on income',
    notes: 'Waitlists may apply. Apply as early as possible.',
    needsVerification: true,
    verifyNote: 'Eligibility, waitlist status, and income limits change. Verify current program rules.',
    priority: 3,
    urgentFlag: false,
  },

  /* ============================================================
     DOCUMENT ASSISTANCE
  ============================================================ */
  {
    id: 'id-access',
    name: 'ID Access — Washington State ID Assistance',
    category: 'documents',
    tags: ['id', 'documents', 'identification', 'barrier', 'statewide'],
    description: 'Help obtaining state ID or driver\'s license for people experiencing homelessness or housing instability.',
    phone: '211',
    phone_alt: null,
    website: null,
    hours: 'Varies by provider',
    languages: 'Varies',
    eligibility: 'People experiencing homelessness or unable to afford ID fees',
    cost: 'ID fees may be waived or covered for eligible individuals',
    notes: 'Ask 211 for local ID assistance programs. Some shelters and day centers also help with IDs.',
    needsVerification: true,
    verifyNote: 'ID assistance programs vary by provider and location. Verify via 211.',
    priority: 2,
    urgentFlag: false,
  },

  /* ============================================================
     TRANSPORTATION
  ============================================================ */
  {
    id: 'orca-lift',
    name: 'ORCA LIFT — Reduced-Fare Transit',
    category: 'transportation',
    tags: ['transportation', 'transit', 'reduced-fare', 'king-county'],
    description: 'ORCA LIFT provides half-price transit fares on King County Metro and other transit for eligible low-income riders.',
    phone: '206-553-3000',
    phone_alt: null,
    website: null,
    hours: 'Business hours',
    languages: 'Multiple languages',
    eligibility: 'Income at or below 200% of federal poverty level (Needs Verification)',
    cost: 'Reduced fares (~$1.50 per ride; Needs Verification)',
    notes: 'Apply through King County Metro or social service agencies.',
    needsVerification: true,
    verifyNote: 'Eligibility thresholds and fares change. Verify current ORCA LIFT requirements.',
    priority: 3,
    urgentFlag: false,
  },

  /* ============================================================
     LANGUAGE ACCESS
  ============================================================ */
  {
    id: 'language-access',
    name: 'Language Access — Translation & Interpretation',
    category: 'access',
    tags: ['language', 'interpreter', 'translation', 'access'],
    description: 'Under federal and Washington State law, many programs must provide free language assistance. If you need an interpreter, ask any service provider — you have the right to request one.',
    phone: '211',
    phone_alt: null,
    website: null,
    hours: 'Request at any service appointment',
    languages: 'All languages',
    eligibility: 'Anyone with limited English proficiency accessing publicly-funded services',
    cost: 'Free (providers are required to provide)',
    notes: 'You should not need to bring your own interpreter. Ask any agency: "I need an interpreter in [language]."',
    needsVerification: false,
    priority: 3,
    urgentFlag: false,
  },
];

export function getResourcesByCategory(category) {
  return resources.filter(r => r.category === category);
}

export function getResourcesByTags(tags) {
  return resources.filter(r =>
    tags.some(tag => r.tags.includes(tag))
  );
}

export function getUrgentResources() {
  return resources.filter(r => r.urgentFlag);
}

export function matchResources(barriers, profile) {
  const tagMap = {
    domestic_violence: ['domestic-violence', 'safety'],
    eviction_history: ['legal-aid', 'tenant-rights', 'eviction'],
    rental_debt: ['rental-assistance', 'eviction-prevention'],
    utility_arrears: ['utilities'],
    no_income: ['rental-assistance', 'benefits', 'food'],
    low_income: ['affordable-housing', 'rental-assistance'],
    missing_id: ['id', 'documents'],
    disability_barrier: ['disability', 'fair-housing', 'accommodation'],
    voucher_discrimination: ['fair-housing', 'tenant-rights'],
    language_barrier: ['language'],
    childcare_barrier: ['childcare', 'family'],
    transportation_barrier: ['transportation'],
    mental_health: ['mental-health', 'health'],
    food_insecurity: ['food', 'basic-needs'],
    homeless: ['shelter', 'coordinated-entry', 'crisis'],
  };

  const allTags = new Set(['crisis', 'referral']);

  barriers.forEach(barrier => {
    const tags = tagMap[barrier] || [];
    tags.forEach(t => allTags.add(t));
  });

  if (profile?.hasChildren) {
    allTags.add('family');
    allTags.add('children');
  }

  if (profile?.hasDisability) {
    allTags.add('disability');
  }

  if (profile?.fleeSafety) {
    allTags.add('domestic-violence');
    allTags.add('safety');
  }

  return resources
    .filter(r => r.tags.some(t => allTags.has(t)))
    .sort((a, b) => a.priority - b.priority);
}
