const BASE='https://raw.githubusercontent.com/decodedjustice-design/housingtrack-scanner/main/';
const files=['availability_results.json','properties_scoped.json','external_leads.json','inventory_audit.json'];
const state={view:'dashboard',availability:[],properties:[],external:[],audit:null,query:'',city:'all',program:'all',status:'all'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const val=(o,...keys)=>{for(const k of keys){if(o&&o[k]!=null&&o[k]!=='')return o[k]}return null};
function badge(status){const s=String(status||'unknown').toLowerCase();let c=s.includes('available')?'available':s.includes('wait')?'waitlist':s==='error'?'error':s==='review'?'review':'unknown';return `<span class="badge ${c}">${esc(status||'unknown')}</span>`}
function money(x){return x==null?'—':`$${Number(x).toLocaleString()}`}
function date(x){if(!x)return '—';const d=new Date(x);return isNaN(d)?esc(x):d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
async function load(){
  const [a,p,e,au]=await Promise.all(files.map(async f=>{try{const r=await fetch(BASE+f+'?t='+Date.now());return await r.json()}catch{return null}}));
  state.availability=Array.isArray(a)?a:(a?.results||[]); state.properties=Array.isArray(p)?p:(p?.properties||[]); state.external=Array.isArray(e)?e:(e?.leads||[]); state.audit=au||{}; render();
}
function filtered(){return state.availability.filter(x=>{const d=x.details||{};const text=JSON.stringify(x).toLowerCase();const city=val(x,'city')||val(d,'city')||'';const program=String(val(x,'programs')||d.programs||'').toLowerCase();return (!state.query||text.includes(state.query.toLowerCase()))&& (state.city==='all'||city.toLowerCase()===state.city)&& (state.program==='all'||program.includes(state.program))&& (state.status==='all'||String(x.status||'unknown').toLowerCase().includes(state.status))})}
function stats(){const f=state.availability;return `<div class="grid stats"><div class="card"><div class="stat-label">Monitored properties</div><div class="stat-value">${state.properties.length||'—'}</div><div class="stat-note">Current scoped inventory</div></div><div class="card"><div class="stat-label">Confirmed available</div><div class="stat-value">${f.filter(x=>x.status==='available').length}</div><div class="stat-note">Scanner-confirmed signals</div></div><div class="card"><div class="stat-label">Needs verification</div><div class="stat-value">${f.filter(x=>x.eligibility==='review'||x.status==='unknown').length}</div><div class="stat-note">Not represented as current availability</div></div><div class="card"><div class="stat-label">External leads</div><div class="stat-value">${state.external.length}</div><div class="stat-note">Leads only — official verification required</div></div></div>`}
function dashboard(){const recent=[...state.availability].sort((a,b)=>new Date(b.checked_at||0)-new Date(a.checked_at||0)).slice(0,8);return stats()+`<div class="notice"><b>Evidence rule:</b> marketplace results are leads, and unknown/error records are never presented as confirmed availability. Check the source before acting.</div><div class="grid two"><div class="card"><h2 class="section-title">Latest scanner results</h2>${recent.length?recent.map(x=>`<div class="property"><div><div class="property-name">${esc(x.property_name||x.name||'Unnamed property')}</div><div class="muted">${esc(x.city||'King County')} · ${esc((x.programs||[]).join?.(', ')||x.eligibility||'Program verification')}</div></div><div>${badge(x.status)}<div class="muted" style="text-align:right;margin-top:5px">${date(x.checked_at)}</div></div></div>`).join(''):'<div class="empty">No scanner records loaded.</div>'}</div><div class="card"><h2 class="section-title">Source health</h2><div class="property"><span>Official property sources</span><b>${state.availability.filter(x=>x.status!=='error').length}</b></div><div class="property"><span>Blocked/error records</span><b>${state.availability.filter(x=>x.status==='error').length}</b></div><div class="property"><span>Last observed check</span><b>${date(Math.max(...state.availability.map(x=>new Date(x.checked_at||0).getTime()).filter(Boolean)))}</b></div></div></div>`}
function availability(){const rows=filtered();const cities=[...new Set(state.availability.map(x=>String(x.city||'').trim()).filter(Boolean))].sort();return `<div class="toolbar"><input id="q" class="field search" placeholder="Search property, feature, source..." value="${esc(state.query)}"><select id="city" class="field"><option value="all">All cities</option>${cities.map(c=>`<option value="${esc(c.toLowerCase())}" ${state.city===c.toLowerCase()?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="program" class="field"><option value="all">All programs</option><option value="arch" ${state.program==='arch'?'selected':''}>ARCH</option><option value="mfte" ${state.program==='mfte'?'selected':''}>MFTE</option></select><select id="status" class="field"><option value="all">All statuses</option><option value="available">Available</option><option value="unknown">Unknown</option><option value="wait">Waitlist</option><option value="error">Error</option></select></div><div class="table-wrap"><table><thead><tr><th>Property</th><th>City</th><th>Program / eligibility</th><th>Status</th><th>Rent</th><th>Sq ft</th><th>Checked</th></tr></thead><tbody>${rows.slice(0,300).map(x=>{const d=x.details||{};return `<tr><td><b>${esc(x.property_name||x.name||'—')}</b></td><td>${esc(x.city||'—')}</td><td>${esc((x.programs||[]).join?.(', ')||x.eligibility||'verification needed')}</td><td>${badge(x.status)}</td><td>${money(d.rent||d.rents?.[0])}</td><td>${esc(d.sqft||'—')}</td><td>${date(x.checked_at)}</td></tr>`}).join('')||`<tr><td colspan="7"><div class="empty">No records match these filters.</div></td></tr>`}</tbody></table></div>`}
function properties(){return `<div class="toolbar"><input id="pq" class="field search" placeholder="Search properties..." value="${esc(state.query)}"></div><div class="grid two">${state.properties.slice(0,200).map(p=>`<div class="card"><div class="property-name">${esc(p.property_name||p.name||'Unnamed')}</div><div class="muted">${esc(p.city||'')} ${p.address?'· '+esc(p.address):''}</div><div class="chips">${(p.programs||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')||'<span class="chip">Program verification needed</span>'}${p.excluded?'<span class="chip">Excluded</span>':''}</div></div>`).join('')}</div>`}
function sources(){const urls=new Map();state.availability.forEach(x=>(x.pages_checked||[]).forEach(u=>urls.set(u,x.checked_at)));state.external.forEach(x=>{if(x.url)urls.set(x.url,x.checked_at||x.found_at)});return `<div class="card"><h2 class="section-title">Monitored and discovered sources</h2><div class="source-row head"><span>Source</span><span>Status</span><span>Last check</span><span>Type</span></div>${[...urls.entries()].slice(0,250).map(([u,t])=>`<div class="source-row"><span><a href="${esc(u)}" target="_blank" rel="noreferrer">${esc(u)}</a></span><span>${badge('checked')}</span><span>${date(t)}</span><span>${u.includes('craigslist')||u.includes('zumper')?'External lead':'Official/public'}</span></div>`).join('')||'<div class="empty">No source URLs available.</div>'}</div>`}
function alerts(){const a=state.availability.filter(x=>x.status==='available');return `<div class="notice"><b>Alert readiness:</b> the scanner already records availability changes. This view is intentionally conservative until alert delivery is connected to a user preference and notification channel.</div><div class="card"><h2 class="section-title">Potential alerts</h2>${a.length?a.map(x=>`<div class="property"><div><div class="property-name">${esc(x.property_name||x.name)}</div><div class="muted">${esc(x.city||'')} · ${esc((x.programs||[]).join?.(', ')||'program verification')}</div></div><div>${badge('available')}<div class="muted" style="margin-top:5px">${date(x.checked_at)}</div></div></div>`).join(''):'<div class="empty">No confirmed availability signals in the current scan.</div>'}</div>`}
function render(){const v=state.view;$('#title').textContent=v[0].toUpperCase()+v.slice(1);$('#content').innerHTML=v==='dashboard'?dashboard():v==='availability'?availability():v==='properties'?properties():v==='sources'?sources():alerts();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));['q','city','program','status','pq'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('input',()=>{if(id==='q'||id==='pq')state.query=el.value;else state[id]=el.value;render()})})}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render()}));$('#refresh').addEventListener('click',load);load();